version: "3.3"

services:
  backend:
    restart: always
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - "80:80"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    restart: always
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=django_postgres
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password

volumes:
  postgres_data: